# This is a basic workflow that is triggered on a daily basis
name: Daily Workflow

on:
  workflow_dispatch:
  schedule:
    # This syntax means to execute the workflow everyday at UTC noon
    - cron:  '0 12 * * *'

jobs:
  tweet:
    runs-on: ubuntu-latest
    # This job contains three steps
    steps:
      # The first step checks out auto-tweets in order to access "today_status.txt"
      - uses: actions/checkout@v2
      # The second step sets NEW_STATUS with either "today_status.txt" or a timestamp
      - name: Set the status to post to twitter
        run: |
          NEW_STATUS="$(date '+%FT%T')"
          [ -f today_status.txt ] && NEW_STATUS="$(tr -d '\r' < today_status.txt | tr '\n' ' ')"
          echo "NEW_STATUS=$NEW_STATUS" >> $GITHUB_ENV
        shell: bash
      # The third step tweets NEW_STATUS using "Send Tweet Action" by Edward Thomson
      - uses: ethomson/send-tweet-action@v1.0.0
        with:
          # The status ("tweet") to post to twitter.
          status: ${{ env.NEW_STATUS }}
          consumer-key: ${{ secrets.TWITTER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_API_KEY_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
